# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emacs Redux
author: Bozhidar Batsov
email: bozhidar@emacsredux.com
description: >- # this means to ignore newlines until "baseurl:"
  Return to the Essence of Text Editing
permalink: "blog/:year/:month/:day/:title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emacsredux.com" # the base hostname & protocol for your site, e.g. http://example.com

# Some defaults that get applied to all posts, so you don't have repeat them
# in the post metadata.
# More details here https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
 - scope:
     path: "" # an empty string here means all files in the project
     type: "posts"
   values:
     author: "Bozhidar Batsov"

twitter_username: bbatsov
github_username:  bbatsov
rss: rss

# disqus:
#   shortname: emacsredux
google_analytics: UA-39624961-1

show_excerpts: true
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
#remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

## Hydeout config
# sidebar_home_link:  true
# paginate: 5

# jekyll-feed config
feed:
  path: atom.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
